Proyectofinal/Proyectofinal/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path("", include('Teveo.urls')),
    path("admin/", admin.site.urls),
]

Proyectofinal/Teveo/urls.py
from django.urls import path

from . import views

urlpatterns = [
   path('', views.index, name='index'),
    path('css', views.get_css, name='get_css'),
    path('camaras', views.camaras, name='camaras'),
    path('comentario-dyn', views.get_coment_dyn, name='coment_dyn'),
    path('comentario', views.get_coment, name='coment'),
    path('imagen', views.get_img, name='imagen'),
    path('configuracion', views.config, name='config'),
    path('ayuda', views.ayuda, name='ayuda'),
    path('img_random',views.get_random_image, name='get_image'),
    path('change_img', views.change_img),
    path('change_comm', views.change_comm),
    path('time',views.get_time),
    path('<str:id>.json', views.get_json, name='get_json'),
    path('<str:id>-dyn', views.get_camara_dyn, name='get_dyn'),
    path('<str:id>', views.get_camara, name='get_camara'),
]

Proyectofinal/Teveo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Camara(models.Model):
    ident = models.CharField(max_length=25)
    nombre = models.CharField(max_length=60)
    url = models.URLField()  # cambiar a URLField
    localizacion = models.TextField()
    imagen = models.BinaryField(
        blank=True, null=True)

    def __str__(self):
        return str(self.ident) + ' :' + self.nombre + ', ' + self.url + ', ' + self.localizacion

class Perfil(models.Model):
    nombre = models.CharField(max_length=40, default='Anónimo')
    cookie = models.TextField(default='')
    FUENTE = [('serif', 'serif'),
              ('monospace', 'monospace'),
              ('italic', 'italic'),
              ('cursive', 'cursive'),
              ('fantasy', 'fantasy'),
              ('math', 'math')]
    letra = models.CharField(max_length=25, default='italic', choices=FUENTE)
    TAMANYO = [('x-small', 'Extra pequeño'),
               ('small', 'Pequeño'),
               ('medium', 'Normal'),
               ('large', 'Grande'),
               ('x-large', 'Extra grande')]
    tamanyo = models.CharField(default='medium', max_length=10, choices=TAMANYO)

    def __str__(self):
        return self.nombre + ', cookie: ' + self.cookie + ', tamaño y fuente: ' + self.tamanyo + ', ' + self.letra
class Comentario(models.Model):
    camara = models.ForeignKey(Camara, on_delete=models.CASCADE)
    texto = models.TextField(blank=False, max_length=200)
    imagen = models.BinaryField()
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.camara.ident) + ': ' + self.texto + ', ' + str(self.fecha)





class Like(models.Model):
    camara = models.ForeignKey(Camara, on_delete=models.CASCADE)
    user = models.ForeignKey(Perfil, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.camara) + str(self.user)

Proyectofinal/Teveo/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Comentario, Perfil

class ComentForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto']
        labels = {'texto': ''}
        widgets = {
            "texto": forms.Textarea(
                attrs={"cols": 10, "rows": 10, "class": 'form-control', 'placeholder': 'Introduzca aquí su comentario'}),
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['nombre', 'letra', 'tamanyo']
        labels = {'nombre': '', 'letra': '', 'tamanyo': ''}
        widgets = {
            'nombre': forms.TextInput(attrs={'placeholder': 'Ingrese su nombre'}),
        }

Proyectofinal/Teveo/views.py
import json
import random
import string
import urllib.request
from .parserXml1 import XML_1
from .parserXml2 import XML_2
from .parserGalicia import Json_Galicia
from .parserEuskadi import Json_Euskadi
from datetime import datetime, timedelta
from .forms import ComentForm, UserForm
from .models import Perfil, Camara, Comentario, Like
from django.db.models import Count
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string

def paginacion(lista, numero, n_pagina):
    paginator = Paginator(lista, numero)
    page_obj = paginator.get_page(n_pagina)
    return page_obj

def get_time(request):
    time = datetime.now().strftime("%Y-%b-%d %H:%M:%S")
    return HttpResponse(time)
def get_nombre(request):
    nombre = 'Anónimo'
    if 'cookie_teveo' in request.COOKIES:
        if Perfil.objects.filter(cookie=request.COOKIES['cookie_teveo']):
            nombre = Perfil.objects.filter(cookie=request.COOKIES['cookie_teveo'])[0].nombre
    return nombre
def index(request):
    comentarios_set = Comentario.objects.all().order_by('fecha').reverse()
    contexto = {'nombre': get_nombre(request), 'pagina': paginacion(comentarios_set, 5, request.GET.get('page')),
                'num_cam': Camara.objects.all().count(),
                'num_comment': Comentario.objects.all().count()}
    return render(request, 'plantillas/index.html', contexto)
def get_css(request):
    letra = 'italic'
    tamanyo = 'normal'
    if 'cookie_teveo' in request.COOKIES:
        if Perfil.objects.filter(cookie=request.COOKIES['cookie_teveo']):
            perfil = Perfil.objects.get(cookie=request.COOKIES['cookie_teveo'])
            letra = perfil.letra
            tamanyo = perfil.tamanyo
    css = render_to_string('css/css_perfil.css', {'letra': letra, 'tamanyo': tamanyo})
    return HttpResponse(css, content_type='text/css')
def camaras(request):
    if request.method == 'POST':
        if request.POST['action'] == 'Listado 1':
            stream = urllib.request.urlopen(
                'https://gitlab.eif.urjc.es/cursosweb/2023-2024/final-teveo/-/raw/main/listado1.xml')
            cameras = XML_1(stream).camaras()
        elif request.POST['action'] == 'Listado 2':
            stream = urllib.request.urlopen(
                'https://gitlab.eif.urjc.es/cursosweb/2023-2024/final-teveo/-/raw/main/listado2.xml')
            cameras = XML_2(stream).camaras()
        elif request.POST['action'] == 'Listado 3':
            cameras = Json_Galicia(
                'https://servizos.meteogalicia.gal/mgrss/observacion/jsonCamaras.action').camaras()
        elif request.POST['action'] == 'Listado 4':
            cameras = Json_Euskadi(
                'https://opendata.euskadi.eus/contenidos/ds_localizaciones/camaras_trafico/opendata/camaras-trafico'
                '.json').camaras()
        if cameras:
            for camara in cameras:

                if not camara['id'] in Camara.objects.values_list('ident',
                                                                  flat=True):
                    Camara(ident=camara['id'], nombre=camara['name'], url=camara['url'].replace(' ', ''),
                           localizacion=camara['coordenadas']).save()
    camaras_populares = Camara.objects.annotate(num_comment=Count('comentario')).order_by('-num_comment')
    contexto = {'nombre': get_nombre(request), 'pagina': paginacion(camaras_populares, 15, request.GET.get('page')),
                'num_cam': Camara.objects.all().count(),
                'num_comment': Comentario.objects.all().count()}
    return render(request, 'plantillas/camaras.html', contexto)

def descargar_img(url):##
    cabecera = {
        'User-Agent': 'Mozilla/5.0 (X11; U; Linux i686) Gecko/20071127 Firefox/2.0.0.11'
    }
    request = urllib.request.Request(url=url, headers=cabecera)
    try:
        with urllib.request.urlopen(request) as response:
            image = response.read()
    except urllib.error.URLError:
        return None
    return image

def get_random_image(request):
    random.seed()
    camara_random = Camara.objects.all()[random.randint(0, Camara.objects.all().count() - 1)]
    camara_random.imagen = descargar_img(camara_random.url)
    camara_random.save()
    return HttpResponse(camara_random.imagen, content_type='image/jpeg')

def get_json(request, id):
    try:
        camara = Camara.objects.get(ident=id)
        camara_dict = {
            'identificador': camara.ident,
            'nombre': camara.nombre,
            'latitud': camara.localizacion.split(',')[1],
            'longitud': camara.localizacion.split(',')[0],
            'url': camara.url,
            'Numero de comentarios': camara.comentario_set.all().count(),
            'Numero de likes': camara.like_set.all().count()
        }
        json_camara = json.dumps(camara_dict, indent=4)
        return HttpResponse(json_camara, content_type='application/json')
    except Camara.DoesNotExist:
        return render(request, 'plantilla/error.html',
                      {'nombre': get_nombre(request), 'error_message': 'No existe esa camara.',
                       'num_cam': Camara.objects.all().count(),
                       'num_comment': Comentario.objects.all().count()})
def change_comm(request):
    if 'id' in request.GET:
        try:
            comentarios = Comentario.objects.all().filter(camara__ident=request.GET.get('id')).order_by('-fecha')
            contexto = {'comentarios': comentarios}
            return render(request, 'plantilla/coment-dyn.html', contexto)
        except Camara.DoesNotExist:
            return render(request, 'plantilla/error.html',
                          {'nombre': get_nombre(request), 'error_message': 'No existe esa camara.',
                           'num_cam': Camara.objects.all().count(),
                           'num_comment': Comentario.objects.all().count()})
def change_img(request):
    if 'id' in request.GET:
        try:
            print(request.GET.get('id'))
            camara = Camara.objects.get(ident=request.GET.get('id'))
            html_imagen = (f'<img src="/imagen?idImg={camara.ident}&{random.randrange(10000)}" alt ="Imagen de la '
                           f'cámara {camara.ident} ">')
        except Camara.DoesNotExist:
            html_imagen = ''
        return HttpResponse(html_imagen)

def get_img(request):
    imagen = ''
    if 'idComent' in request.GET:
        imagen = Comentario.objects.get(pk=request.GET.get('idComent')).imagen
    elif 'idImg' in request.GET:
        camara = Camara.objects.get(ident=request.GET.get('idImg'))
        camara.imagen = descargar_img(camara.url)
        imagen = camara.imagen
        camara.save()
    return HttpResponse(imagen, content_type='image/jpeg')
def get_css(request):
    letra = 'italic'
    tamanyo = 'normal'
    if 'cookie_teveo' in request.COOKIES:
        if Perfil.objects.filter(cookie=request.COOKIES['cookie_teveo']):
            perfil = Perfil.objects.get(cookie=request.COOKIES['cookie_teveo'])
            letra = perfil.letra
            tamanyo = perfil.tamanyo
    css = render_to_string('css/css_perfil.css', {'letra': letra, 'tamanyo': tamanyo})
    return HttpResponse(css, content_type='text/css')
def get_camara_view(request, id, template_name):
    if request.method == 'POST':
        if request.POST.get('action') == 'Me gusta':
            like = Like.objects.filter(camara=Camara.objects.get(ident=id),
                                       user__cookie=request.COOKIES['cookie_teveo'])
            if not like:
                Like.objects.create(camara=Camara.objects.get(ident=id),
                                    user=Perfil.objects.get(cookie=request.COOKIES['cookie_teveo']))

    try:
        cookie = ''
        camara = Camara.objects.get(ident=id)
        comentarios = Comentario.objects.filter(camara__ident=id).order_by('-fecha')
        if 'cookie_teveo' in request.COOKIES:
            cookie = request.COOKIES['cookie_teveo']
        contexto = {
            'nombre': get_nombre(request),
            'camara': camara,
            'pagina': paginacion(comentarios, 3, request.GET.get('page')),
            'num_cam': Camara.objects.count(),
            'num_comment': Comentario.objects.count(),
            'likes': Like.objects.filter(camara=Camara.objects.get(ident=id)).count(),
            'register': Perfil.objects.filter(cookie=cookie)
        }
        return render(request, template_name, contexto)

    except Camara.DoesNotExist:
        return render(request, 'plantillas/error.html',
                      {'nombre': get_nombre(request), 'error_message': 'No existe esa camara.',
                       'num_cam': Camara.objects.all().count(),
                       'num_comment': Comentario.objects.all().count()})
def get_camara(request, id):
    return get_camara_view(request, id, 'plantillas/camara.html')


def get_camara_dyn(request, id):
    return get_camara_view(request, id, 'plantillas/dynamic.html')
def ayuda(request):
    contexto = {'nombre': get_nombre(request),
                'num_cam': Camara.objects.all().count(),
                'num_comment': Comentario.objects.all().count()}
    return render(request, 'plantillas/ayuda.html', contexto)
def comentario(request, redireccion):
    try:
        camara = Camara.objects.get(ident=request.GET['id'])
        if request.method == "POST":
            form = ComentForm(request.POST)
            if form.is_valid():
                new_coment = form.save(commit=False)
                new_coment.camara = camara
                new_coment.imagen = camara.imagen
                new_coment.save()
                return redirect(redireccion, id=request.GET['id'])
        return render(request, 'plantillas/coment.html',
                      {'nombre': get_nombre(request), 'form': ComentForm, 'camara': camara,

Proyectofinal/Teveo/templates/plantillas/ayuda.html
{% extends 'plantillas/main.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
        <div class="row mt-5">
            <div class="col-12">
                <h3 class="4 text-capitalize text-decoration-underline">Autoria</h3>
                <div>Practica hecha por Raul molina Lopez. </div>
                 <h3 class="4 text-capitalize text-decoration-underline">Resumen </h3>
                <div>Esta practica cosniste en la creacion de una aplicacion web mediante django en la que podemos observar distintas camaras de España. </div>

                <dl class="list-group">
                    <h3 class="4 text-capitalize text-decoration-underline">Paginas</h3>
                    <div class="list-group-item">
                        <dt class="bolder mb-2 mt-1">'/'</dt>
                        <dd>Pagina principal nos aparece un mensaje de bienvenida asi como aparece las camaras con comentarios de la mas nueva a la mas vieja   </dd>
                    </div>
                    <div class="list-group-item">
                        <dt class="bolder mb-2 mt-1">'/camaras'</dt>
                        <dd>En este recurso tenemos cuatro botones,  al pulsarlos se descargarán la información de
                            distintos archivos de datos. apareceuna imagen escogida aleatoriamente
                            de entre todas las cámaras de la base de datos en el centro, ademas apareceran las distintas camaras en tabla.</dd>
                    </div>
                    <div class="list-group-item">
                        <dt class="bolder mb-2 mt-1">'/{id_camara}':</dt>
                        <dd>Página estática de la camara, aparece la iagen de la camara de cuando se pidio ,nos aparece
                            la información de la cámara, el número de likes y los comentarios ordenados segun su fecha de publicación,ademas podemos accecder a la camara dinamica asi como el acceso a poner comentarios
                            si el usuario tiene un nombre dejara delr a like .</dd>
                    </div>
                    <div class="list-group-item">
                        <dt class="bolder mb-2 mt-1">'/{id_camara}-dyn'</dt>
                        <dd>pagina de la camara dinamica hace lo mismo que la camara estatica pero se actualiza </dd>
                    </div>
                    <div class="list-group-item">
                        <dt class="bolder mb-2 mt-1">'/comentario?id={id_camara}'</dt>
                        <dd>Donde escribimos los comentarios</dd>
                    </div>
                    <div class="list-group-item">
                        <dt class="bolder mb-2 mt-1">'/{id_camara}.json'</dt>
                        <dd>Donde se crea el json de la camara solicitada</dd>
                    </div>
                    <div class="list-group-item">
                        <dt class="bolder mb-2 mt-1">'/configuracion'</dt>
                        <dd>Desde esta pagina tenemos acceso a la personalizacion del perfil.</dd>
                    </div>
                </dl>
            </div>
        </div>
    </div>
{% endblock %}

Proyectofinal/Teveo/templates/plantillas/camara.html
{% extends 'plantillas/main.html' %}
{% load static %}

{% block content %}
    {% if camara %}
        <div class="container py-4">
            <div class="row mb-4">
                {% block titulo %}{% endblock %}
                <div class="col-10">
                    <h5 class="text-capitalize">{{ camara.nombre }}</h5>
                    <p class="mb-0">Localizado en {{ camara.localizacion }}</p>
                </div>
                <div class="col-2">
                    <img class="icon" src="{% static 'imagenes/Gusta.png' %}" alt="Likes"><p> Likes: {{ likes }}</p>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col-12 text-center">
                    <img src="/imagen?idImg={{ camara.ident }}" alt="Imagen de la cámara {{ camara.ident }}" class="img-fluid">
                </div>
            </div>
            <div class="row mb-4 justify-content-center text-center">
            {% block comentarios %}
                <div class="col-4">
                    <a href="{% url 'get_dyn' id=camara.ident %}" class="btn btn-primary btn-lg me-md-2 mb-2 mb-md-0">Ver página dinámica</a>
                </div>
                <div class="col-4">
                    <a href="/comentario?id={{ camara.ident }}" class="btn btn-infobtn-lg">poner un comentario</a>
                </div>
                {% if register %}
                    <div class="col-4">
                        <form action="" method="post">
                            {% csrf_token %}
                            <button class="btn btn-success btn-lg" type="submit" name="action" value="Me gusta" id="like">Me gusta</button>
                        </form>
                    </div>
                {% endif %}
            {% endblock %}
            </div>
            {% block coment %}
                <div class="row">
                    <div class="col-12">
                        {% if pagina %}
                            <ul class="list-group border-top border-bottom">
                                {% for comment in pagina %}
                                    <li class="list-group-item">
                                        <div class="row">
                                            <div class="col-md-7">
                                                <h3>{{ comment.texto }}</h3>
                                                <span class="text-muted">{{ comment.fecha }}</span>
                                            </div>
                                            <div class="col-md-5 text-center">
                                                <img class="img-fluid" src="/imagen?idComent={{ comment.pk }}" alt="Imagen del comentario {{ comment.pk }}">
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                            <nav aria-label="Page navigation" class="mt-4">
                                <ul class="pagination justify-content-center">
                                    {% if pagina.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page=1">&laquo; Primero</a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ pagina.previous_page_number }}">Anterior</a>
                                        </li>
                                    {% endif %}
                                    <li class="page-item disabled">
                                        <span class="page-link">Página {{ pagina.number }} de {{ pagina.paginator.num_pages }}</span>
                                    </li>
                                    {% if pagina.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ pagina.next_page_number }}">Siguiente</a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ pagina.paginator.num_pages }}">Último &raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        {% else %}
                            <p class="text-center">No hay comentarios</p>
                        {% endif %}
                    </div>
                </div>
            {% endblock %}
        </div>
    {% else %}
        <div class="container py-4">
            <div class="row">
                <div class="col-12 text-center">
                    <p>Error: Cámara no encontrada.</p>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

Proyectofinal/Teveo/templates/plantillas/camaras.html
{% extends 'plantillas/main.html' %}

{% block content %}

    <div class="container py-4">
        <h3 class="text-center">Cámaras</h3>
        <hr>
        <h4 class="text-center text-decoration-underline">Listado de cámaras</h4>
        <div class="row mb-4 justify-content-center text-center">
            <div class="col-md-3">
                <form action="" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-primary btn-block" type="submit" name="action" value="Listado 1">Listado 1</button>
                </form>
            </div>
            <div class="col-md-3">
                <form action="" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-primary btn-block" type="submit" name="action" value="Listado 2">Listado 2</button>
                </form>
            </div>
            <div class="col-md-3">
                <form action="" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-primary btn-block" type="submit" name="action" value="Listado 3">Listado 3 Galicia</button>
                </form>
            </div>
            <div class="col-md-3">
                <form action="" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-primary btn-block" type="submit" name="action" value="Listado 4">Listado 4 Euskadi</button>
                </form>
            </div>
        </div>
        <div class="row">
            {% if pagina %}
                <div class="col-lg-12 d-flex justify-content-center align-items-center">
                    <img class="mb-4" src="{% url 'get_image' %}" alt="Imagen aleatoria">
                </div>
                <div class="col-lg-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Id</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Comentarios</th>
                                <th scope="col">Likes</th>
                                <th scope="col">Página Cámara</th>
                                <th scope="col">Página Dinámica</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for camara in pagina %}
                                <tr>
                                    <td>{{ camara.ident }}</td>
                                    <td>{{ camara.nombre }}</td>
                                    <td>{{ camara.comentario_set.count }}</td>
                                    <td>{{ camara.like_set.count }}</td>
                                    <td><a href="/{{ camara.ident }}">Cámara</a></td>
                                    <td><a href="/{{ camara.ident }}-dyn">Dinámica</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <nav aria-label="Page navigation" class="mt-4">
                    <ul class="pagination justify-content-center">
                        {% if pagina.has_previous %}
                            <li class="page-item"><a class="page-link d-block" href="?page=1">&laquo; Primera</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ pagina.previous_page_number }}">Anterior</a></li>
                        {% endif %}
                        <li class="page-item disabled">
                            <span class="page-link">
                                Página {{ pagina.number }} de {{ pagina.paginator.num_pages }}
                            </span>
                        </li>
                        {% if pagina.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ pagina.next_page_number }}">Siguiente</a></li>
                            <li class="page-item"><a class="page-link d-block" href="?page={{ pagina.paginator.num_pages }}">Última &raquo;</a></li>
                        {% endif %}
                    </ul>
                </nav>
            {% else %}
                <div class="col-md-12">
                    <p class="text-center">No hay cámaras disponibles</p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

Proyectofinal/Teveo/templates/plantillas/coment-dyn.html
<div class="row">
            <div class="col-12">
                {% if comentarios %}
                    <ul  class="list-group border-top border-bottom">
                        {% for comment in comentarios %}
                            <li class="list-group-item">
                                <div class="col-sm row">
                                    <div class="col-md-7">
                                        <h3>{{ comment.texto }}</h3>
                                        <span class="text-muted">{{ comment.fecha }}</span>
                                    </div>
                                    <div class="col-md-5 justify-content-center">
                                        <img class="img-fluid" src="/imagen?idComent={{comment.pk}}" alt="Imagen de la cámara {{ comment.camara.ident }}">
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No hay comentarios</p>
                {% endif %}
            </div>
        </div>
    </div>

Proyectofinal/Teveo/templates/plantillas/coment.html
{% extends 'plantillas/camara.html' %}

{% block titulo %}
    <div class="col-12">
        <h5 class="text-center ">Comenta la camara </h5>
    </div>
{% endblock %}

{% block comentarios %}{% endblock %}

{% block coment %}
    <div class="container mt-4">
            <div class="col-12 mb-3">
                <div hx-get="/time" hx-trigger="load, change, every 1s" hx-target="#reloj" hx-swap="innerHTML" ></div>
                <div class="text-center" id="reloj">hora</div>
            </div>
        <form method="POST" class="cms-form" name="coment">{% csrf_token %}
            <div class="mb-3">
                <label for="id_texto" class="form-label">Texto:</label>
                {{ form.texto }}
            </div>
            <button class="btn btn-primary" type="submit">Guardar</button>
        </form>
    </div>
{% endblock %}

Proyectofinal/Teveo/templates/plantillas/configuracion.html
{% extends 'plantillas/main.html' %}
{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <h5 class="text-center text-decoration-underline">Configura tu perfil de TeVeO</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <form method="POST" class="cms-form" name="coment">{% csrf_token %}
                    <div class="mb-3">
                        <label for="id_nombre" class="form-label">Nombre:</label>
                        {{ form.nombre }}
                    </div>
                    <div class="mb-3">
                        <label for="id_letra" class="form-label">Fuente:</label>
                        {{ form.letra }}
                    </div>
                    <div class="mb-3">
                        <label for="id_tamaño" class="form-label">Tamaño:</label>
                        {{ form.tamanyo }}
                    </div>
                    <button class="btn btn-primary" type="submit" name="action" value="Guardar">Guardar</button>
                </form>
            </div>
            <div class="col-md-4 d-flex align-items-end justify-content-md-end">
                <button class="btn btn-outline-secondary"><a href="/configuracion?transferir=1" class="text-info">Ver clave</a></button>
            </div>
            <div class="col-md-12">
                <p>{{ msg }}</p>
            </div>
            <div class="col-md-12 justify-content-center">
                <form action="" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-danger btn-block" type="submit" name="action" value="Eliminar">Eliminar configuracion</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Proyectofinal/Teveo/templates/plantillas/error.html
{% extends 'plantillas/main.html' %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center text-black">
        <div class="text-center text-danger p-4">
            <h3>Error encontrado:</h3>
            <h6>{{ error_message }}</h6>
        </div>
    </div>
{% endblock %}